import os

from cnavconstants.utils import LOCAL_ADDRESS, SERVICE_PORT

# cnav-bot

BLUETOOTH_PORT = int(os.getenv('BLUETOOTH_PORT', 48630))
LOCAL_BLUETOOTH_ADDRESS = LOCAL_ADDRESS.format(port=BLUETOOTH_PORT)
BLUETOOTH_SERVICE_PORT = SERVICE_PORT.format(port=BLUETOOTH_PORT)

CAMERA_PORT = int(os.getenv('CAMERA_PORT', 48631))
LOCAL_CAMERA_ADDRESS = LOCAL_ADDRESS.format(port=CAMERA_PORT)
CAMERA_SERVICE_PORT = SERVICE_PORT.format(port=CAMERA_PORT)

BOT_PORT = int(os.getenv('BOT_PORT', 48632))
LOCAL_BOT_ADDRESS = LOCAL_ADDRESS.format(port=BOT_PORT)
BOT_SERVICE_PORT = SERVICE_PORT.format(port=BOT_PORT)

# cnav-sense

ENVIRONMENTAL_SENSORS_PORT = int(
    os.getenv('ENVIRONMENTAL_SENSORS_PORT', 48640)
)
LOCAL_ENVIRONMENTAL_SENSORS_ADDRESS = LOCAL_ADDRESS.format(
    port=ENVIRONMENTAL_SENSORS_PORT
)
ENVIRONMENTAL_SENSORS_SERVICE_PORT = SERVICE_PORT.format(
    port=ENVIRONMENTAL_SENSORS_PORT
)


INERTIAL_SENSORS_PORT = int(
    os.getenv('INERTIAL_SENSORS_PORT', 48641)
)
LOCAL_INERTIAL_SENSORS_ADDRESS = LOCAL_ADDRESS.format(
    port=INERTIAL_SENSORS_PORT
)
INERTIAL_SENSORS_SERVICE_PORT = SERVICE_PORT.format(
    port=INERTIAL_SENSORS_PORT
)


JOYSTICK_PORT = int(
    os.getenv('JOYSTICK_PORT', 48642)
)
LOCAL_JOYSTICK_ADDRESS = LOCAL_ADDRESS.format(
    port=JOYSTICK_PORT
)
JOYSTICK_SERVICE_PORT = SERVICE_PORT.format(
    port=JOYSTICK_PORT
)
